[project]
name = "mlops"
version = "0.9.0"
requires-python = ">=3.12"
readme = "README.md"
dependencies = [
    "torch",
    "torchvision",
    "scikit-learn",
    "pandas",
    "matplotlib",
    "Pillow",
    "tqdm",
    "PyYAML",
    "transformers"
]

[project.optional-dependencies]
dev = [
    "ty",
    "ruff",
    "codecov"
]
test = [
    "pytest",
    "pytest-cov"
]

[tool.taskipy.tasks]
lint = "ruff check src tests ; ty check src tests"
fmt  = "ruff format src tests"
test = "pytest tests/ -v"

predict    = "predict"
setup_data = "setup_data"
train      = "train"
validate   = "validate"

[project.scripts]
predict    = "predict:main"
setup_data = "setup_data:main"
train      = "train:main"
validate   = "validate:main"

[build-system]
requires = [
    "setuptools",
    "wheel",
    "taskipy",
    "dvc"
]
build-backend = "setuptools.build_meta"
