[project]
name = "mlops"
version = "0.9.0"
requires-python = ">=3.12"
readme = "README.md"
dependencies = [
    "torch",
    "torchvision",
    "scikit-learn",
    "pandas",
    "matplotlib",
    "Pillow",
    "tqdm",
    "PyYAML",
    "transformers"
]

[project.optional-dependencies]
dev = [
    "ty",
    "ruff",
    "codecov",

    "types-PyYAML" # TODO: remove
]
test = [
    "pytest",
    "pytest-cov"
]

[tool.taskipy.tasks]
lint = "ruff check & ty check"
fmt  = "ruff format"
test = "pytest tests/ -v"

predict    = "predict"
setup_data = "setup_data"
train      = "train"
validate   = "validate"

[project.scripts]
predict    = "predict:main"
setup_data = "setup_data:main"
train      = "train:main"
validate   = "validate:main"

[tool.ruff.lint]
select = [
    "F",        # Pyflakes rules
    "W",        # PyCodeStyle warnings
    "E",        # PyCodeStyle errors
    "I",        # Sort imports properly
    "UP",       # Warn if certain things can changed due to newer Python versions
    "C4",       # Catch incorrect use of comprehensions, dict, list, etc
    "FA",       # Enforce from __future__ import annotations
    "ISC",      # Good use of string concatenation
    "ICN",      # Use common import conventions
    "RET",      # Good return practices
    "SIM",      # Common simplification rules
    "TID",      # Some good import practices
    "TC",       # Enforce importing certain types in a TYPE_CHECKING block
    "PTH",      # Use pathlib instead of os.path
    "TD",       # Be diligent with TODO comments
    "NPY",      # Some numpy-specific things
]
ignore = [
    "G004", "COM812", 
    "TRY003", "EM101", "EM102", "T201",
    "PTH207",
    "D", "S"
]

[build-system]
requires = [
    "setuptools",
    "wheel",
    "taskipy",
    "dvc"
]
build-backend = "setuptools.build_meta"
